# Generated by Django 5.0.6 on 2024-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fly", "0002_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="name",
            name="name",
        ),
        migrations.AddField(
            model_name="fly",
            name="name",
            field=models.ManyToManyField(related_name="name", to="fly.name"),
        ),
    ]
