# Generated by Django 5.0.6 on 2024-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fly", "0003_remove_name_name_fly_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fly",
            name="name",
            field=models.ManyToManyField(related_name="bird", to="fly.name"),
        ),
    ]
