# Generated by Django 5.0.6 on 2024-06-29 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
