# Generated by Django 5.0.6 on 2024-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="release_date",
            field=models.CharField(max_length=255),
        ),
    ]
