# Generated by Django 5.0.6 on 2024-06-30 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_alter_song_release_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="artist_name",
        ),
        migrations.RemoveField(
            model_name="song",
            name="artwork_url",
        ),
        migrations.RemoveField(
            model_name="song",
            name="collection_name",
        ),
        migrations.RemoveField(
            model_name="song",
            name="preview_url",
        ),
        migrations.RemoveField(
            model_name="song",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="song",
            name="track_name",
        ),
    ]
